import { PokemonTypes } from './types';

function findMatchups(type: PokemonTypes): { [key in PokemonTypes]: number } {
  return typeMatchups[type];
}

export function findDualTypeMatchups(type1: PokemonTypes, type2?: PokemonTypes): Record<string, number> {
  const type1Matchups = findMatchups(type1);

  if (!type2) {
    return type1Matchups;
  }

  const type2Matchups = findMatchups(type2);
  const dualTypeMatchups: Record<string, number> = {};

  const keys = Object.keys(PokemonTypes) as Array<keyof typeof PokemonTypes>;

  for (const t of keys) {
    const currentType = PokemonTypes[t];
    dualTypeMatchups[currentType] = 1 / (type1Matchups[currentType] * type2Matchups[currentType]);
  }

  return dualTypeMatchups;
}
const typeMatchups: { [key in PokemonTypes]: { [key in PokemonTypes]: number } } = {
  [PokemonTypes.NORMAL]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 0,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.FIRE]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.WATER]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.ELECTRIC]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 0,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.GRASS]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.ICE]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ICE]: 0.5,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.FIGHTING]: {
    [PokemonTypes.NORMAL]: 2,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 0,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.FAIRY]: 0.5,
  },
  [PokemonTypes.POISON]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0,
    [PokemonTypes.FAIRY]: 2,
  },
  [PokemonTypes.GROUND]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 2,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 0,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.FLYING]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.PSYCHIC]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 0,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.BUG]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 0.5,
  },
  [PokemonTypes.ROCK]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.GHOST]: {
    [PokemonTypes.NORMAL]: 0,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 0,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.DRAGON]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 0,
  },
  [PokemonTypes.DARK]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 0.5,
  },
  [PokemonTypes.STEEL]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 2,
  },
  [PokemonTypes.FAIRY]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
};
